version: '3.7'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongoDC
    environment:
      - 'MONGO_INITDB_DATABASE=admin'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    ports:
      - '27017:27017'
    command: mongod --logpath=/dev/null # --quiet

  kalahagame-app:
    depends_on:
      - mongodb
    build: .
    image: kalahagame:latest
    container_name: kalahaDC
    environment:
      - 'SPRING_DATA_MONGODB_HOST=mongodb'
      - 'SPRING_DATA_MONGODB_PORT=27017'
      - 'SPRING_DATA_MONGODB_USERNAME=root'
      - 'SPRING_DATA_MONGODB_PASSWORD=secret'
      - 'SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin'
    ports:
      - '8080:8080'

  kalaha-ui-outer:
    build: ui/.
    command: sh -c "npm start"
    ports:
      - '80:4200'
